apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-glpi-content
 namespace: glpi
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 8Gi
 storageClassName: nfs-static
