{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "glpi.fullname" . }}-content
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "glpi.labels" . | nindent 4 }}
spec:
  accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
